### PR TITLE
BUG FIX - correct answer failed due to comparing a sting to an Int wi…

### PR DESCRIPTION
**Pull request by BillGilmoreLP**
…th ===

When the user checks if their answer is correct it always fails as it is asking if an string === to an Integer in js/siderModel.js

### CODE REVIEW

**Comment by moloko** [comment]
hi @BillGilmoreLP I'm having trouble replicating this, please could you [log a ticket](https://github.com/adaptlearning/adapt_framework/issues/new) detailing the issue and giving steps to replicate?

**Comment by moloko** [comment]
also it feels a bit wrong dropping the strict equality check; I think it might be better to do `var answer = Number(this.get('_correctAnswer'));` together with a comment explaining that `_correctAnswer` is a string because the AAT won't allow a property with an `""inputType"` of `"Number"` to have no value - which it needs to be able to have when you want to use `_correctRange` instead of `_correctAnswer`

**Comment by BillGilmoreLP** [comment]
Hi @moloko I have created a ticket. I toyed with the idea of using:
`var answer = pasreFloat(this.get('_correctAnswer'));`
but i was worried it might have a knock on later when a string is expected, or with the function set up to correctly handle decimal places.
Thanks for the feedback

**Comment by oliverfoster** [comment]
`answer ? i === Number(answer)` in the ternary would also be fine

**Comment by tomgreenfield** [comment]
@oliverfoster is correct; if we explicitly convert to an integer, it needs to happen after the `answer` truthy check.

**Comment by BillGilmoreLP** [comment]
Great news, glad I could be of some service @moloko and @oliverfoster

**Comment by BillGilmoreLP** [comment]
I'm just checking the status here @moloko do you want / need me to push the fix suggested by @oliverfoster or have you guys done that? Thanks

**Comment by moloko** [comment]
Hi @BillGilmoreLP if you could do it that would be great; as this PR originates from your repository we can't change it without closing the PR and setting up a new one

**Comment by moloko** [comment]
>we can't change it without closing the PR and setting up a new one

or maybe we can, via the online editor? never noticed that before! 

Anyway, have done one of GH's new-fangled code suggestions instead.

**Comment by BillGilmoreLP** [comment]
So should I implement this, or do you want to do it via the online editor @moloko ?
Sorry for the confusion, I marked your suggestion as 'resolved' thinking it would approve your fix into my work. I'm new to GitHub man apologies

**Comment by moloko** [comment]
I've 'unresolved' it...

**Comment by oliverfoster** [comment]
@BillGilmoreLP Could you make the update please.

**Comment by BillGilmoreLP** [comment]
Thats it ready to merge now I think @moloko and @oliverfoster 
Thanks for the assistance, its nice to be able to contribute even in this small way

**Comment by BillGilmoreLP** [comment]
Hi guys can someone merge this please?
"This branch has no conflicts with the base branch
Only those with write access to this repository can merge pull requests."

I don't have the access to do so. @moloko @tomgreenfield @brian-learningpool @nilslp

**Pull request merged**
