### PR TITLE
fix for 'sticky handle' in desktop browsers

### PR DESCRIPTION
**Pull request by moloko**
See [ABU-1112](https://adaptlearning.atlassian.net/browse/ABU-1112)
also remove some of the more pointless comments, add where helpful

### CODE REVIEW

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
oh very pretty! +1

**Comment by moloko** [comment]
I see I've forgotten the version bump, I'll sort that after this is merged in

**Comment by lc-thomasberger** [comment]
+1

**Comment by brian-learningpool** [comment]
+1

**Comment by dancgray** [comment]
+1

**Pull request merged**
