### PR TITLE
Issue/#2283 - fix to show user feedback when number scale is hidden

### PR DESCRIPTION
**Pull request by BillGilmoreLP**
I would appreciate your feedback on the best way to fix Issue #2283.

As the ticket I raised says, when the user hides the number scale, gets the answer wrong, clicks show correct answer, the indicator is hidden so they don't get any feedback.

Resolves https://github.com/adaptlearning/adapt_framework/issues/2283.

### CODE REVIEW

**Comment by BillGilmoreLP** [comment]
Thanks @moloko I had another look into this today. I think this is a good fix. We only call the showModelAnswers function (which shows the answer in the indicator) when _showScaleIndicator is set to true. What do you think? 
https://github.com/adaptlearning/adapt-contrib-slider/commit/1d13bd6e8cbe54a47783b46b6e0fa5bb29cdda3d

**Comment by moloko** [comment]
Hi @BillGilmoreLP it is a good solution - but as I mentioned before I'd prefer to have it dealt with separately from this PR - there's lots of aspects to the process that are much easier if we can keep everything separated out as much as possible.

If you can sort out the indentation, additional spaces and FW dependency we can push ahead with getting review on this PR, then setup an issue for the model answer/_showScaleIndicator issue and deal with that in a separate PR

**Comment by BillGilmoreLP** [comment]
Thanks for your ongoing feedback and support @moloko I think my latest commit fixes the issues you raised. Is there anything else I can do to improve or should I make another ticket to address the '_showScaleIndicator' issue you found?
Thank you

**Comment by moloko** [comment]
> should I make another ticket to address the `_showScaleIndicator` issue you found?

If you have time, that would be great.

**Pull request merged**
