### PR TITLE
Update to latest version of rangeslider.js and fix various RTL issues

### PR DESCRIPTION
**Pull request by NayanKhedkar**
fixes https://github.com/adaptlearning/adapt_framework/issues/1318, https://github.com/adaptlearning/adapt_framework/issues/1597 and https://github.com/adaptlearning/adapt_framework/issues/1350

### CODE REVIEW

**Comment by effernity** [comment]
Hello!
IE 11 gives an error when bookmarking is on and slider question is answered.
SCRIPT5007: Unable to get value of the property 'prop': object is null or undefined
adapt.min.js, string: 84, column: 2306
image

**Comment by effernity** [comment]
BTW, in Google Chrome there is the same error:
Uncaught TypeError: Cannot read property 'prop' of undefined
    at B.n.setAllItemsEnabled (adapt.min.js:84)
    at B.n.disableQuestion (adapt.min.js:84)
    at B.n.onEnabledChanged (adapt.min.js:83)
    at b (adapt.min.js:76)
    at v (adapt.min.js:76)
    at d (adapt.min.js:76)
    at B.n.u.trigger (adapt.min.js:76)
    at B.n.set (adapt.min.js:76)
    at B.n.set (adapt.min.js:77)
    at B.n.setQuestionAsSubmitted (adapt.min.js:81)

**Comment by moloko** [comment]
Hi @effernity - can I just check, are you saying that the changes in this pull request cause this issue?

**Comment by effernity** [comment]
Hello @moloko , no, i just couldn't find where to leave issue

**Comment by moloko** [comment]
@effernity there's a link in bower.json

**Comment by effernity** [comment]
@moloko oh, thanks a lot!

**Comment by sarveshwar-gavhane** [comment]
can we wait till https://github.com/andreruffert/rangeslider.js/pull/245 this PR gets merged into rangeSlider first ? , otherwise every time when we upgrade the rangeSlider we have to manually make the changes for RTL.

**Comment by brian-learningpool** [comment]
@NayanKhedkar, is it possible for you to respond to @tomgreenfield's comments on andreruffert/rangeslider.js#245?  This PR has been hanging around for some time.

**Comment by NayanKhedkar** [comment]
@brian-learningpool and @tomgreenfield initial css no more required.I updated css on same PR.

**Comment by moloko** [comment]
Once https://github.com/andreruffert/rangeslider.js/pull/245 is merged and we can come back to this again, please can we make sure to test against the framework using JQuery 3.1.x to check that version of JQuery doesn't still cause [this bug](https://github.com/adaptlearning/adapt_framework/issues/1441)?

**Comment by moloko** [comment]
OK well there's been very little movement on the rangeslider repo in the past year (just four commits) so I appreciate what @sarveshwar-gavhane is saying I do thing we should just go ahead and then manually amend for the RTL fixes. 
hopefully getting this in will also allow us to finally update to JQuery v3.

**Comment by sarveshwar-gavhane** [comment]
sounds good @moloko and this PR has been hanging around near about a year(December to nov) now, i don't think so range Slider does care about RTL as we do in Adapt, they are not interested to either reviewing or merging 
i think we should move ahead if everyone is happy.

**Comment by NayanKhedkar** [comment]
I have updated the latest rangeslider.js(v2.3.1) with few changes to rtl feature. So can we go ahead and merge this PR, instead of waiting for the PR: https://github.com/andreruffert/rangeslider.js/pull/245 to merge. @moloko @tomgreenfield @brian-learningpool  can you please review the PR?

**Pull request merged**
