### PR TITLE
Fixes #90, bug with _correctRange when _correctAnswer is undefined

### LINKED ISSUE #90: Control flow bug when using _correctRange
There's a bug in the following line which prevents answer ranges from working as expected:
https://github.com/adaptlearning/adapt-contrib-slider/blob/master/js/adapt-contrib-slider.js#L48

If answer is `undefined` it still enters this `if`statement.

### PR DESCRIPTION
**Pull request by brian-learningpool**
When _correctAnswer was undefined the _correctRange would not work.

This patch fixes the control flow bug to check for undefined or an
empty string.

### CODE REVIEW

**Comment by brian-learningpool** [comment]
Hi @tomgreenfield, thanks for reviewing. It works as expected with  `_correctAnswer` of "0".

**Comment by ciaranlp** [comment]
+1

**Comment by moloko** [comment]
+1

**Comment by tomgreenfield** [comment]
@brian-learningpool, yes it works as expected when entering the number as a String. Out of curiousity, is there a particular reason that this is the only numerical value that is expected to be a String on this model? If we use the approach [above](https://github.com/adaptlearning/adapt-contrib-slider/pull/91#commitcomment-14585863) then we also wouldn't have to worry about changing the [type](https://github.com/adaptlearning/adapt-contrib-slider/pull/92/files#diff-4517165ffe55c65dfed48457eadd2d1cR104) in the schema.

**Comment by moloko** [comment]
I was wondering about that too, it does seem a little odd that it's been set to expect a string in #85 - do we not run the risk of the user entering something non-numerical?

**Comment by moloko** [comment]
maybe this is just another thing to add to the pile to fix when we really sort out this component

**Comment by brian-learningpool** [comment]
@tomgreenfield, I can't say.  It seems we're missing some kind of a 'mode', whereby there's either a valid range or a correct answer.  Whoever wrote it appears to have used an empty string (`_correctAnswer`) for that flag.

Anyway, I'm not precious about it. I didn't write the plugin, just doing my best to fix what I can.

**Comment by moloko** [comment]
I'm happy for us to run with this for now then sort it out properly as part of the overhaul of Slider

**Comment by dennis-learningpool** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
