### PR TITLE
Added SCORM interactions support.

### PR DESCRIPTION
**Pull request by chris-steele**
https://adaptlearning.atlassian.net/browse/ABU-690

### CODE REVIEW

**Comment by taylortom** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by moloko** [comment]
I think 'numeric' would be a better value for `cmi.interaction.n.type` for this question type

example.json and README need updating to include `_recordInteraction`

**Comment by hrajotia** [comment]
+1

**Comment by dancgray** [comment]
+1

**Comment by hrajotia** [comment]
+1

**Comment by taylortom** [comment]
+1

**Pull request merged**
