### PR TITLE
Issue 1111

### PR DESCRIPTION
**Pull request by ryan-lynch**
The ariaLabels on buttons must be of inputType QuestionButton

### CODE REVIEW

**Comment by bell87** [comment]
+1

**Comment by oliverfoster** [comment]
Is this supported in NVDA JAWS and VoiceOver?

**Comment by moloko** [comment]
I've not heard of this input type before... do you have any more information about it you can share? 

it would be useful to include the [properties.schema how-to wiki page](https://github.com/adaptlearning/adapt_authoring/wiki/Properties-Schema)

(also, without knowing what impact the change has I feel I'm not qualified to review it)

**Comment by brian-learningpool** [comment]
@moloko, @oliverfoster, the input type is used in the authoring too here:
https://github.com/adaptlearning/adapt_authoring/blob/master/frontend/src/core/scaffold/views/scaffoldQuestionButtonView.js

I've updated the original ticket with a bit of background info.

**Comment by oliverfoster** [comment]
sorry, i'm clearly misunderstanding

**Comment by oliverfoster** [comment]
carry on - i'm being an idiot

**Comment by oliverfoster** [comment]
+1

**Comment by moloko** [comment]
+1

**Pull request merged**
