### PR TITLE
Fix: missing attribute values causing runtime error

### LINKED ISSUE #204: Missing default attribute values can cause range input display issues or runtime errors
As there is no default value for `_scaleStart` and `_scaleEnd`, the following error will occur if either are omitted from the JSON:
```JavaScript
SliderView.js:35 Uncaught TypeError: Cannot read properties of null (reading 'index')
    at SliderView.getIndexFromValue (SliderView.js:35:13)
    at Slider (slider.jsx:49:25)
    at templates.<computed> (reactHelpers.js:17:19)
    at renderWithHooks (react-dom.development.js:15015:20)
    at mountIndeterminateComponent (react-dom.development.js:17841:15)
    at beginWork (react-dom.development.js:19079:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at beginWork$1 (react-dom.development.js:23994:9)
```

For a confidence slider the runtime error isn't immediately shown, but a missing  `_scaleStart` (if using `_linkedToId` it will attempt to retrieve these values from the linked model) causes the input display to be out of sync with the value (presumably because it defaults to the default 0 `min` of `<input type="range">`. If `_scaleEnd` is missing the scale is displayed incorrectly and the following error occurs when interacting with the slider:
```JavaScript
SliderView.js:35 Uncaught TypeError: Cannot read properties of null (reading 'index')
    at ConfidenceSliderView.getIndexFromValue (SliderView.js:35:13)
    at ConfidenceSliderView.onNumberSelected (ConfidenceSliderView.js:34:24)
    at onChange (confidenceSlider.jsx:190:28)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3942:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3991:18)
    at invokeGuardedCallback (react-dom.development.js:4053:33)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4067:27)
    at executeDispatch (react-dom.development.js:8273:5)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8305:9)
    at processDispatchQueue (react-dom.development.js:8318:7)
```

The schema default for `_scaleEnd` should also be changed from 1.

### PR DESCRIPTION
**Pull request by danielghost**
Fixes #204.

### Fix
* Added default attribute values for `_scaleStart`, `_scaleEnd` and `_scaleStep`.
* Restrict `_scaleStep` to a positive number.

### Update
* Changed  `_scaleEnd` schema default from 1 to 10.

### CODE REVIEW

**Review by oliverfoster — COMMENTED** [review]
Will _scaleStep set to 0 work?

**Comment by danielghost** [comment]
> Will _scaleStep set to 0 work?

Good catch, this will need safeguarding against due to https://github.com/adaptlearning/adapt-contrib-slider/pull/205/commits/bee1e3bae02e14e6dba251449edf7d277522c80b. Also need to restrict this to positive numbers only.

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

**Review by oliverfoster — APPROVED** [review]

**Review by guywillis — APPROVED** [review]
👀

**Pull request merged**
